/**
 * Priority A prospect list from Caantin Global ICP v3.
 *
 * Organized by outbound cluster — each cluster gets a different Matt Lawler pitch.
 * Phone numbers need to be filled in from LinkedIn / company websites.
 *
 * To call a batch:
 *   POST /api/outbound/batch
 *   Authorization: Bearer <OUTBOUND_API_SECRET>
 *   Body: { prospects: [ { phoneNumber, name, company, cluster } ] }
 */

export interface Prospect {
  company: string
  country: string
  category: string
  website: string
  cluster: 'post-acquisition' | 'public-npl' | 'massive-scale' | 'regulator-pressure' | 'bnpl' | 'default'
  icpNotes: string
  // Fill these in from LinkedIn outreach
  contactName?: string
  contactTitle?: string
  contactPhone?: string
  contactLinkedIn?: string
}

// ── POST-ACQUISITION ─────────────────────────────────────────────
// New owners scrutinizing the loan book. Urgency is high.
export const POST_ACQUISITION: Prospect[] = [
  {
    company: 'Baobab',
    country: 'Nigeria/Multi',
    category: 'MFI / Digital Lender',
    website: 'baobab.com',
    cluster: 'post-acquisition',
    icpNotes: 'Just acquired by Beltone (Feb 2026). New owner NPL scrutiny = hot signal.',
  },
  {
    company: 'ZestMoney',
    country: 'India',
    category: 'BNPL / EMI Finance',
    website: 'zestmoney.in',
    cluster: 'post-acquisition',
    icpNotes: 'PhonePe acquired. Large BNPL book. Known delinquency challenges.',
  },
  {
    company: 'Slice (NE Small Finance Bank)',
    country: 'India',
    category: 'Credit Card / BNPL',
    website: 'sliceit.in',
    cluster: 'post-acquisition',
    icpNotes: 'Merged with NE SFB. Large delinquent book.',
  },
]

// ── PUBLIC NPL PRESSURE ──────────────────────────────────────────
// Listed companies where NPL shows up in earnings. Board pressure.
export const PUBLIC_NPL: Prospect[] = [
  {
    company: 'Affirm',
    country: 'USA',
    category: 'BNPL',
    website: 'affirm.com',
    cluster: 'public-npl',
    icpNotes: 'Nasdaq listed. BNPL leader. Growing delinquency rate.',
  },
  {
    company: 'Klarna',
    country: 'Sweden',
    category: 'BNPL',
    website: 'klarna.com',
    cluster: 'public-npl',
    icpNotes: '$14B IPO. 150M global users. Delinquency at scale.',
  },
  {
    company: 'OppFi (OppLoans)',
    country: 'USA',
    category: 'Subprime Digital Lender',
    website: 'oppfi.com',
    cluster: 'public-npl',
    icpNotes: 'NYSE listed. Subprime consumer. High NCO rates.',
  },
  {
    company: 'OneMain Financial',
    country: 'USA',
    category: 'Consumer Lender',
    website: 'onemainfinancial.com',
    cluster: 'public-npl',
    icpNotes: 'NYSE listed. 2.9M customers. High NCO pressure.',
  },
  {
    company: 'Enova International',
    country: 'USA',
    category: 'Subprime Digital Lender',
    website: 'enova.com',
    cluster: 'public-npl',
    icpNotes: 'Nasdaq listed. CashNetUSA, NetCredit brands. Subprime focus.',
  },
  {
    company: 'Dave',
    country: 'USA',
    category: 'Digital Bank / Cash Advance',
    website: 'dave.com',
    cluster: 'public-npl',
    icpNotes: 'Nasdaq listed. 10M+ users. Very high volume, very low ticket.',
  },
  {
    company: 'Oportun',
    country: 'USA',
    category: 'Digital Lender (underserved)',
    website: 'oportun.com',
    cluster: 'public-npl',
    icpNotes: 'Nasdaq listed. 2M+ customers. Hispanic/underserved market.',
  },
  {
    company: 'MoneyLion',
    country: 'USA',
    category: 'Digital Bank / Lender',
    website: 'moneylion.com',
    cluster: 'public-npl',
    icpNotes: 'NYSE listed. 4M+ users. Multiple lending products.',
  },
  {
    company: 'Sezzle',
    country: 'USA',
    category: 'BNPL',
    website: 'sezzle.com',
    cluster: 'public-npl',
    icpNotes: 'Nasdaq listed. Classic delinquency profile.',
  },
  {
    company: 'Capitec Bank',
    country: 'South Africa',
    category: 'Digital Bank / Lender',
    website: 'capitecbank.co.za',
    cluster: 'public-npl',
    icpNotes: 'JSE Listed. 17M+ clients. Massive consumer credit book.',
  },
  {
    company: 'Zip',
    country: 'Australia/Multi',
    category: 'BNPL',
    website: 'zip.co',
    cluster: 'public-npl',
    icpNotes: 'ASX listed. Global operations. NPL pressure.',
  },
  {
    company: 'Nubank',
    country: 'Brazil/Multi',
    category: 'Neobank / Consumer Credit',
    website: 'nubank.com.br',
    cluster: 'public-npl',
    icpNotes: "World's largest neobank. 110M+ customers. Credit delinquency at scale.",
  },
  {
    company: 'Letshego',
    country: 'Botswana/Multi',
    category: 'Consumer Lender',
    website: 'letshego.com',
    cluster: 'public-npl',
    icpNotes: 'JSE Listed. 11 countries. Large delinquent book.',
  },
  {
    company: 'Finbond Group',
    country: 'South Africa',
    category: 'Micro-lender',
    website: 'finbond.com',
    cluster: 'public-npl',
    icpNotes: 'JSE Listed. Micro-lending, SA + North America ops.',
  },
]

// ── MASSIVE SCALE ────────────────────────────────────────────────
// 10M+ users. Can't hire enough agents. Volume is the pain.
export const MASSIVE_SCALE: Prospect[] = [
  {
    company: 'OPay',
    country: 'Nigeria',
    category: 'Neobank / Super App',
    website: 'opayweb.com',
    cluster: 'massive-scale',
    icpNotes: '$2B valuation. 50M+ users. Consumer lending arm growing.',
  },
  {
    company: 'PalmPay',
    country: 'Nigeria',
    category: 'Neobank / Digital Wallet',
    website: 'palmpay.com',
    cluster: 'massive-scale',
    icpNotes: 'Transsion-backed. 35M users. Consumer loans + credit services.',
  },
  {
    company: 'Moniepoint',
    country: 'Nigeria',
    category: 'Neobank / SME Lender',
    website: 'moniepoint.com',
    cluster: 'massive-scale',
    icpNotes: '$1B+ valuation. 10M+ users. Business + individual lending.',
  },
  {
    company: 'GCash (Fuse Lending)',
    country: 'Philippines',
    category: 'Super App / Digital Lender',
    website: 'gcash.com',
    cluster: 'massive-scale',
    icpNotes: '80M+ users. GCredit/GLoan embedded lending.',
  },
  {
    company: 'bKash',
    country: 'Bangladesh',
    category: 'Mobile Money / Lender',
    website: 'bkash.com',
    cluster: 'massive-scale',
    icpNotes: "Bangladesh's largest MFS. 82M users. Lending arm growing.",
  },
  {
    company: 'MoMo (Vietnam)',
    country: 'Vietnam',
    category: 'Digital Wallet / Lender',
    website: 'momo.vn',
    cluster: 'massive-scale',
    icpNotes: '30M+ users. Wallet-embedded credit.',
  },
  {
    company: 'KreditBee',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'kreditbee.in',
    cluster: 'massive-scale',
    icpNotes: '30M+ users. RBI pressure on NPLs.',
  },
  {
    company: 'Kuda Bank',
    country: 'Nigeria',
    category: 'Neobank / Digital Lender',
    website: 'kuda.com',
    cluster: 'massive-scale',
    icpNotes: '7M+ users. Consumer credit (overdraft, salary loans).',
  },
  {
    company: 'TymeBank',
    country: 'South Africa',
    category: 'Neobank / Lender',
    website: 'tymebank.co.za',
    cluster: 'massive-scale',
    icpNotes: "$1.5B val. SA's first fully digital bank. 10M+ customers.",
  },
  {
    company: 'Tala',
    country: 'Kenya/Multi',
    category: 'Digital Lender',
    website: 'tala.co',
    cluster: 'massive-scale',
    icpNotes: 'VC-backed (Visa, a16z). 6M+ customers across Africa.',
  },
  {
    company: 'Branch',
    country: 'Nigeria/Multi',
    category: 'Digital Lender',
    website: 'branch.co',
    cluster: 'massive-scale',
    icpNotes: 'A16z-backed. 5M+ customers Africa. High volume, low ticket.',
  },
  {
    company: 'Carbon (OneFi)',
    country: 'Nigeria',
    category: 'Digital Bank / Lender',
    website: 'getcarbon.co',
    cluster: 'massive-scale',
    icpNotes: '5M+ users. One of Nigeria\'s original digital lenders.',
  },
  {
    company: 'FairMoney',
    country: 'Nigeria',
    category: 'Digital Bank / Lender',
    website: 'fairmoney.africa',
    cluster: 'massive-scale',
    icpNotes: 'EXISTING CUSTOMER. 17M downloads. 10K loans/day.',
  },
  {
    company: 'Paytm (lending arm)',
    country: 'India',
    category: 'Super App / Lending',
    website: 'paytm.com',
    cluster: 'massive-scale',
    icpNotes: 'Paytm Postpaid + consumer loans. Massive user base.',
  },
  {
    company: 'SeaMoney (ShopeePay)',
    country: 'Indonesia/Multi',
    category: 'Super App / Digital Lender',
    website: 'seamoney.com',
    cluster: 'massive-scale',
    icpNotes: 'Sea Group embedded BNPL/credit. Huge regional scale.',
  },
  {
    company: 'GoPay Later (GoTo)',
    country: 'Indonesia',
    category: 'BNPL',
    website: 'gojek.com',
    cluster: 'massive-scale',
    icpNotes: 'GoTo embedded credit. Massive scale within super-app.',
  },
  {
    company: 'MNT-Halan',
    country: 'Egypt',
    category: 'Digital Lender / Super App',
    website: 'mnt-halan.com',
    cluster: 'massive-scale',
    icpNotes: "Egypt's unicorn. 8M+ customers. $4.4B disbursed.",
  },
  {
    company: 'M-Kopa',
    country: 'Kenya/Multi',
    category: 'PAYG Asset Finance',
    website: 'm-kopa.com',
    cluster: 'massive-scale',
    icpNotes: '4M+ customers. Recurring collection challenge by design.',
  },
  {
    company: 'Fuliza (Safaricom/NCBA/KCB)',
    country: 'Kenya',
    category: 'Mobile Overdraft',
    website: 'safaricom.co.ke',
    cluster: 'massive-scale',
    icpNotes: 'Largest digital credit product in Kenya. 1.6B+ loans/yr.',
  },
  {
    company: 'JazzCash',
    country: 'Pakistan',
    category: 'Mobile Money / Lender',
    website: 'jazzcash.com.pk',
    cluster: 'massive-scale',
    icpNotes: "Pakistan's largest mobile wallet. 15M+ users.",
  },
  {
    company: 'Easypaisa',
    country: 'Pakistan',
    category: 'Mobile Money / Digital Bank',
    website: 'easypaisa.com.pk',
    cluster: 'massive-scale',
    icpNotes: '15M+ users. Digital bank licence pilot. Consumer lending.',
  },
  {
    company: 'Mercado Crédito',
    country: 'Argentina/Multi',
    category: 'Digital Lender',
    website: 'mercadopago.com',
    cluster: 'massive-scale',
    icpNotes: 'MercadoLibre credit arm. Enormous book.',
  },
]

// ── REGULATOR PRESSURE ───────────────────────────────────────────
// Regulators cracking down on collections practices.
export const REGULATOR_PRESSURE: Prospect[] = [
  {
    company: 'AdaKami',
    country: 'Indonesia',
    category: 'Digital Lender',
    website: 'adakami.id',
    cluster: 'regulator-pressure',
    icpNotes: 'P2P consumer, flagged for high NPL by OJK.',
  },
  {
    company: 'Akulaku',
    country: 'Indonesia/Multi',
    category: 'BNPL / Digital Lender',
    website: 'akulaku.com',
    cluster: 'regulator-pressure',
    icpNotes: 'Multi-market BNPL. High NPL under OJK scrutiny.',
  },
  {
    company: 'Kredivo',
    country: 'Indonesia',
    category: 'BNPL / Digital Lender',
    website: 'kredivo.com',
    cluster: 'regulator-pressure',
    icpNotes: "Indonesia's largest BNPL. Massive delinquency challenge.",
  },
  {
    company: 'Navi Technologies',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'navi.com',
    cluster: 'regulator-pressure',
    icpNotes: 'Sachin Bansal backed. RBI oversight.',
  },
  {
    company: 'Fibe (EarlySalary)',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'fibe.in',
    cluster: 'regulator-pressure',
    icpNotes: 'Salary advance + personal loans. Large delinquent book. RBI regulated.',
  },
  {
    company: 'Kissht',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'kissht.com',
    cluster: 'regulator-pressure',
    icpNotes: 'Consumer + device finance. RBI regulated.',
  },
]

// ── BNPL ─────────────────────────────────────────────────────────
// BNPL-specific: high volume, low ticket, can't collect manually.
export const BNPL: Prospect[] = [
  {
    company: 'Klarna US',
    country: 'USA',
    category: 'BNPL',
    website: 'klarna.com',
    cluster: 'bnpl',
    icpNotes: '34M US users. Material delinquency growing.',
  },
  {
    company: 'Clearpay (Afterpay UK)',
    country: 'United Kingdom',
    category: 'BNPL',
    website: 'clearpay.co.uk',
    cluster: 'bnpl',
    icpNotes: "Afterpay's UK arm. 5M+ UK users.",
  },
  {
    company: 'Zilch',
    country: 'United Kingdom',
    category: 'BNPL',
    website: 'zilch.com',
    cluster: 'bnpl',
    icpNotes: '5M+ customers. FCA regulated. 30-day interest-free.',
  },
  {
    company: 'Scalapay',
    country: 'Italy',
    category: 'BNPL',
    website: 'scalapay.com',
    cluster: 'bnpl',
    icpNotes: 'Fastest growing EU BNPL. Large delinquent book.',
  },
  {
    company: 'Tabby',
    country: 'UAE / Saudi Arabia',
    category: 'BNPL',
    website: 'tabby.ai',
    cluster: 'bnpl',
    icpNotes: 'MENA BNPL co-leader. 10M+ users.',
  },
  {
    company: 'Tamara',
    country: 'Saudi Arabia',
    category: 'BNPL',
    website: 'tamara.co',
    cluster: 'bnpl',
    icpNotes: 'Fastest growing MENA BNPL. 10M+ users.',
  },
  {
    company: 'Afterpay',
    country: 'Australia',
    category: 'BNPL',
    website: 'afterpay.com',
    cluster: 'bnpl',
    icpNotes: 'BNPL giant. 20M+ AU users.',
  },
  {
    company: 'Lipa Later',
    country: 'Kenya/Multi',
    category: 'BNPL',
    website: 'lipalater.com',
    cluster: 'bnpl',
    icpNotes: 'B2C BNPL, delinquency growing with scale.',
  },
  {
    company: 'BillEase',
    country: 'Philippines',
    category: 'BNPL',
    website: 'billease.ph',
    cluster: 'bnpl',
    icpNotes: 'BNPL, growing delinquency.',
  },
  {
    company: 'Atome',
    country: 'Singapore/Multi',
    category: 'BNPL',
    website: 'atome.sg',
    cluster: 'bnpl',
    icpNotes: 'Pan-SEA BNPL. Significant delinquency at scale.',
  },
  {
    company: 'PayJustNow',
    country: 'South Africa',
    category: 'BNPL',
    website: 'payjustnow.co.za',
    cluster: 'bnpl',
    icpNotes: 'SA BNPL leader. Interest-free installments.',
  },
  {
    company: 'Humm',
    country: 'Australia',
    category: 'BNPL',
    website: 'humm.com.au',
    cluster: 'bnpl',
    icpNotes: 'Consumer BNPL. NCR regulated in NZ.',
  },
  {
    company: 'Laybuy',
    country: 'United Kingdom',
    category: 'BNPL',
    website: 'laybuy.com',
    cluster: 'bnpl',
    icpNotes: 'NZ-originating BNPL, UK operations.',
  },
  {
    company: 'Addi',
    country: 'Colombia/Brazil',
    category: 'BNPL',
    website: 'addipayments.com',
    cluster: 'bnpl',
    icpNotes: 'LatAm BNPL leader.',
  },
  {
    company: 'LazyPay',
    country: 'India',
    category: 'BNPL (PayU)',
    website: 'lazypay.in',
    cluster: 'bnpl',
    icpNotes: 'PayU BNPL arm. Underserved borrowers.',
  },
  {
    company: 'ValU (EFG Hermes)',
    country: 'Egypt',
    category: 'BNPL / Consumer Credit',
    website: 'valu.com.eg',
    cluster: 'bnpl',
    icpNotes: "Egypt's leading BNPL. Large consumer book.",
  },
  {
    company: 'Floa (BNP Paribas)',
    country: 'France',
    category: 'BNPL / Consumer Credit',
    website: 'floapay.com',
    cluster: 'bnpl',
    icpNotes: 'BNP-owned BNPL. Massive French consumer book.',
  },
  {
    company: 'RCS Group',
    country: 'South Africa',
    category: 'Consumer Credit / BNPL',
    website: 'rcs.co.za',
    cluster: 'bnpl',
    icpNotes: 'Retail credit + BNPL. BNP Paribas owned.',
  },
  {
    company: 'Lucky One',
    country: 'Egypt',
    category: 'Consumer Credit / BNPL',
    website: 'lucky.one',
    cluster: 'bnpl',
    icpNotes: 'Consumer credit + rewards. Large Cairo delinquency pool.',
  },
]

// ── DEFAULT (HIGH-VALUE DIGITAL LENDERS) ─────────────────────────
// Strong ICP fit, no specific trigger cluster.
export const DEFAULT_PROSPECTS: Prospect[] = [
  // Nigeria
  {
    company: 'Renmoney',
    country: 'Nigeria',
    category: 'Digital Lender',
    website: 'renmoney.com',
    cluster: 'default',
    icpNotes: 'Personal loans to salaried workers. Classic high-NPL ICP.',
  },
  {
    company: 'Page Financials',
    country: 'Nigeria',
    category: 'Digital Lender',
    website: 'pagefinancials.com',
    cluster: 'default',
    icpNotes: 'Salaried consumer loans. Classic ICP.',
  },
  {
    company: 'Palmcredit',
    country: 'Nigeria',
    category: 'Digital Lender',
    website: 'palmcredit.com',
    cluster: 'default',
    icpNotes: 'Newedge Finance. Device + nano + large credit products.',
  },
  {
    company: 'QuickCheck',
    country: 'Nigeria',
    category: 'Digital Lender',
    website: 'quickcheck.ng',
    cluster: 'default',
    icpNotes: 'AI credit scoring. High-volume consumer.',
  },
  {
    company: 'OxygenX',
    country: 'Nigeria',
    category: 'Digital Lender',
    website: 'oxygenx.com',
    cluster: 'default',
    icpNotes: 'EXISTING CUSTOMER. Core ICP reference.',
  },
  // Kenya
  {
    company: 'Watu Credit',
    country: 'Kenya/Uganda',
    category: 'Asset Finance',
    website: 'watucredit.com',
    cluster: 'default',
    icpNotes: 'Boda boda + auto financing. Collections-intensive.',
  },
  {
    company: 'Zenka',
    country: 'Kenya',
    category: 'Digital Lender',
    website: 'zenkafinance.com',
    cluster: 'default',
    icpNotes: 'Fast-growing app lender.',
  },
  {
    company: 'KCB M-Pesa',
    country: 'Kenya',
    category: 'Mobile Loan',
    website: 'kcbgroup.com',
    cluster: 'default',
    icpNotes: 'High-volume low-ticket mobile loans. 3.8M monthly actives.',
  },
  {
    company: 'M-Shwari (Safaricom/NCBA)',
    country: 'Kenya',
    category: 'Mobile Savings/Loans',
    website: 'safaricom.co.ke',
    cluster: 'default',
    icpNotes: 'Pioneer Kenya digital credit. 4.7M monthly actives.',
  },
  {
    company: 'EazzyLoan (Equity Bank)',
    country: 'Kenya',
    category: 'Mobile Loan',
    website: 'equitybankgroup.com',
    cluster: 'default',
    icpNotes: 'Equity Bank mobile lending. Massive reach via Equitel.',
  },
  // South Africa
  {
    company: 'African Bank',
    country: 'South Africa',
    category: 'Consumer Lender',
    website: 'africanbank.co.za',
    cluster: 'default',
    icpNotes: 'Specialist consumer lender. Large delinquent book.',
  },
  {
    company: 'Bayport Financial Services',
    country: 'South Africa',
    category: 'Payroll Lender',
    website: 'bayportsa.com',
    cluster: 'default',
    icpNotes: 'Pan-Africa payroll lending.',
  },
  {
    company: 'Capfin',
    country: 'South Africa',
    category: 'Consumer Lender',
    website: 'capfin.co.za',
    cluster: 'default',
    icpNotes: 'Micro-lender, large delinquent book.',
  },
  {
    company: 'DirectAxis',
    country: 'South Africa',
    category: 'Consumer Lender',
    website: 'directaxis.co.za',
    cluster: 'default',
    icpNotes: 'FirstRand subsidiary. Large consumer personal loan book.',
  },
  {
    company: 'Old Mutual Finance',
    country: 'South Africa',
    category: 'Consumer Lender',
    website: 'oldmutualfinance.co.za',
    cluster: 'default',
    icpNotes: 'Large consumer book under Old Mutual Group.',
  },
  {
    company: 'Wonga SA',
    country: 'South Africa',
    category: 'Short-term Digital Lender',
    website: 'wonga.co.za',
    cluster: 'default',
    icpNotes: 'High-volume short-term consumer.',
  },
  {
    company: 'GetBucks',
    country: 'South Africa',
    category: 'Digital Lender',
    website: 'getbucks.co.za',
    cluster: 'default',
    icpNotes: 'Consumer loans. Pan-Africa footprint.',
  },
  {
    company: 'Jumo',
    country: 'South Africa/Multi',
    category: 'Embedded Lender',
    website: 'jumo.world',
    cluster: 'default',
    icpNotes: 'Embedded in mobile money platforms. Very high volume.',
  },
  // Egypt
  {
    company: 'Kashat',
    country: 'Egypt',
    category: 'Digital Lender',
    website: 'kashat.com.eg',
    cluster: 'default',
    icpNotes: 'First nano-lender in Egypt. Massive volume.',
  },
  {
    company: 'Khazna',
    country: 'Egypt',
    category: 'Digital Lender',
    website: 'khazna.io',
    cluster: 'default',
    icpNotes: 'Payroll + consumer lending. 500K users.',
  },
  // Ghana
  {
    company: 'Fido Money',
    country: 'Ghana/Uganda',
    category: 'Digital Lender',
    website: 'fido.money',
    cluster: 'default',
    icpNotes: 'App-only lender expanding across Africa.',
  },
  // UK
  {
    company: 'Abound',
    country: 'United Kingdom',
    category: 'Digital Lender',
    website: 'abound.co.uk',
    cluster: 'default',
    icpNotes: 'AI consumer credit. Underserved borrowers. $601M funding.',
  },
  {
    company: 'Creditspring',
    country: 'United Kingdom',
    category: 'Digital Lender',
    website: 'creditspring.co.uk',
    cluster: 'default',
    icpNotes: 'Subscription loan model. High-risk borrowers.',
  },
  {
    company: 'Koyo Loans',
    country: 'United Kingdom',
    category: 'Digital Lender',
    website: 'koyoloans.com',
    cluster: 'default',
    icpNotes: 'Open banking underwriting. Growing consumer book.',
  },
  {
    company: 'Lendable',
    country: 'United Kingdom',
    category: 'Digital Lender',
    website: 'lendable.co.uk',
    cluster: 'default',
    icpNotes: 'PE-backed consumer lender. Large delinquent book.',
  },
  {
    company: 'Zopa',
    country: 'United Kingdom',
    category: 'Digital Bank / Lender',
    website: 'zopa.com',
    cluster: 'default',
    icpNotes: 'Large consumer credit book. $900M funding. FCA regulated.',
  },
  // USA
  {
    company: 'Avant',
    country: 'USA',
    category: 'Digital Personal Lender',
    website: 'avant.com',
    cluster: 'default',
    icpNotes: 'Mid-prime personal loans. 1.5M customers.',
  },
  {
    company: 'Best Egg (Marlette)',
    country: 'USA',
    category: 'Digital Personal Lender',
    website: 'bestegg.com',
    cluster: 'default',
    icpNotes: 'Large personal loan book. Growing subprime exposure.',
  },
  {
    company: 'Brigit',
    country: 'USA',
    category: 'Cash Advance / Lender',
    website: 'hellobrigit.com',
    cluster: 'default',
    icpNotes: 'Subscription cash advances. 4M users.',
  },
  {
    company: 'EarnIn',
    country: 'USA',
    category: 'Earned Wage Access',
    website: 'earnin.com',
    cluster: 'default',
    icpNotes: 'Wage advances at scale. 8M+ users.',
  },
  {
    company: 'LendingPoint',
    country: 'USA',
    category: 'Digital Personal Lender',
    website: 'lendingpoint.com',
    cluster: 'default',
    icpNotes: 'Near-prime consumer. Growing book.',
  },
  {
    company: 'Merrick Bank',
    country: 'USA',
    category: 'Consumer Credit (subprime)',
    website: 'merrickbank.com',
    cluster: 'default',
    icpNotes: 'Large subprime consumer book.',
  },
  {
    company: 'NetCredit (Enova)',
    country: 'USA',
    category: 'Subprime Digital Lender',
    website: 'netcredit.com',
    cluster: 'default',
    icpNotes: "Enova's direct-to-consumer subprime brand.",
  },
  {
    company: 'Possible Finance',
    country: 'USA',
    category: 'Short-term Digital Lender',
    website: 'possiblefinance.com',
    cluster: 'default',
    icpNotes: 'Installment loans, underserved consumers.',
  },
  // EU
  {
    company: 'Cofidis',
    country: 'France/Multi',
    category: 'Consumer Credit',
    website: 'cofidis.fr',
    cluster: 'default',
    icpNotes: 'Large EU multi-country consumer credit book.',
  },
  {
    company: 'Ferratum',
    country: 'Finland/Multi',
    category: 'Digital Lender',
    website: 'ferratumbank.com',
    cluster: 'default',
    icpNotes: 'Pan-EU short-term lending. High NPL.',
  },
  {
    company: 'Younited Credit',
    country: 'France',
    category: 'Digital Personal Lender',
    website: 'younited-credit.com',
    cluster: 'default',
    icpNotes: 'AI consumer lending across EU.',
  },
  // MENA
  {
    company: 'MNT-Halan (UAE/Turkey)',
    country: 'UAE/Turkey',
    category: 'Digital Lender / BNPL',
    website: 'mnt-halan.com',
    cluster: 'default',
    icpNotes: 'Expanding from Egypt. Turkey + UAE.',
  },
  // SEA
  {
    company: 'Julo',
    country: 'Indonesia',
    category: 'Digital Lender',
    website: 'julo.co.id',
    cluster: 'default',
    icpNotes: 'AI credit scoring. High-volume consumer.',
  },
  {
    company: 'Cashalo',
    country: 'Philippines',
    category: 'Digital Lender',
    website: 'cashalo.com',
    cluster: 'default',
    icpNotes: 'High-volume consumer loans.',
  },
  {
    company: 'Maya (PayMaya)',
    country: 'Philippines',
    category: 'Digital Bank / Lender',
    website: 'maya.ph',
    cluster: 'default',
    icpNotes: 'Massive user base. Maya credit product growing.',
  },
  {
    company: 'Tonik',
    country: 'Philippines',
    category: 'Digital Bank / Lender',
    website: 'tonikbank.com',
    cluster: 'default',
    icpNotes: 'First Philippines digital bank. Growing consumer credit.',
  },
  // India
  {
    company: 'CASHe',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'cashe.co.in',
    cluster: 'default',
    icpNotes: 'Salaried millennial loans.',
  },
  {
    company: 'Dhani (Indiabulls)',
    country: 'India',
    category: 'Digital Lender / Neobank',
    website: 'dhani.com',
    cluster: 'default',
    icpNotes: 'RBI-approved. Millions of users. Consumer credit app.',
  },
  {
    company: 'Moneyview',
    country: 'India',
    category: 'Digital Lender (NBFC)',
    website: 'moneyview.in',
    cluster: 'default',
    icpNotes: 'Consumer personal loans.',
  },
  // LatAm
  {
    company: 'Creditas',
    country: 'Brazil',
    category: 'Digital Lender',
    website: 'creditas.com',
    cluster: 'default',
    icpNotes: 'Large consumer book. $829M funding.',
  },
  {
    company: 'Kueski',
    country: 'Mexico',
    category: 'Digital Lender / BNPL',
    website: 'kueski.com',
    cluster: 'default',
    icpNotes: "Mexico's largest consumer digital lender.",
  },
  {
    company: 'Rappi Credit',
    country: 'Colombia/Multi',
    category: 'Super App / Credit',
    website: 'rappi.com',
    cluster: 'default',
    icpNotes: "Rappi's embedded lending. Massive user base.",
  },
  {
    company: 'Stori',
    country: 'Mexico',
    category: 'Digital Credit Card',
    website: 'storicard.com',
    cluster: 'default',
    icpNotes: 'VC-backed. Underserved market credit card.',
  },
  // Timiza
  {
    company: 'Timiza (Absa)',
    country: 'Kenya',
    category: 'Mobile Loan / Digital Bank',
    website: 'absa.co.ke',
    cluster: 'default',
    icpNotes: 'Absa Kenya mobile lending. High volume salaried borrowers.',
  },
]

// ── ALL PROSPECTS ────────────────────────────────────────────────
export const ALL_PROSPECTS: Prospect[] = [
  ...POST_ACQUISITION,
  ...PUBLIC_NPL,
  ...MASSIVE_SCALE,
  ...REGULATOR_PRESSURE,
  ...BNPL,
  ...DEFAULT_PROSPECTS,
]

// Summary stats
export const PROSPECT_STATS = {
  total: ALL_PROSPECTS.length,
  byCluster: {
    'post-acquisition': POST_ACQUISITION.length,
    'public-npl': PUBLIC_NPL.length,
    'massive-scale': MASSIVE_SCALE.length,
    'regulator-pressure': REGULATOR_PRESSURE.length,
    bnpl: BNPL.length,
    default: DEFAULT_PROSPECTS.length,
  },
  existingCustomers: ALL_PROSPECTS.filter((p) => p.icpNotes.includes('EXISTING CUSTOMER')).length,
}
